Vue.createApp({
    components:{
        'login-component':loginComponent,
        'usuarios-component':usuariosComponent,
        'lectores-component':lectoresComponent,
        'prueba-component':pruebaComponent
    }
})
.mount('#app')